# Generated by Django 3.0 on 2019-12-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Maintenance', 'Maintenance'), ('Distributing', 'Distributing'), ('OnStreet', 'OnStreet')], default='Created', max_length=50)),
                ('fechaultimostatus', models.DateTimeField(auto_now=True)),
                ('fechacreacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Maintenance', 'Maintenance'), ('Distributing', 'Distributing'), ('OnStreet', 'OnStreet')], default='Created', max_length=50)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviliario', to='scooter.Scooter')),
            ],
        ),
    ]
