# Generated by Django 3.0 on 2019-12-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipoUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tipo', to='accounts.TipoUsuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('gerente', 'gerente'), ('administrativo', 'administrativo'), ('usuario', 'usuario')),
            },
        ),
    ]
